# Generated by Django 3.2.6 on 2021-08-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('tel', models.IntegerField(blank=True)),
                ('post_num', models.IntegerField(blank=True)),
            ],
        ),
    ]
