# Generated by Django 3.2.6 on 2021-08-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
