# Generated by Django 3.2.6 on 2022-05-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
