# Generated by Django 3.2.6 on 2022-06-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_kcal',
            field=models.PositiveIntegerField(default=3000),
        ),
    ]
