# Generated by Django 3.2.6 on 2022-06-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_target_kcal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
