# Generated by Django 3.2.6 on 2021-09-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_alter_fitnessactivate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessactivate',
            name='consumed_calories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
