# Generated by Django 3.2.6 on 2021-10-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
        ('calories', '0003_fitnessactivate_consumed_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(default='음식이름', max_length=100)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('calorie', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IncomeFoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion', models.PositiveIntegerField(default=0)),
                ('income_calories', models.PositiveIntegerField(default=0)),
                ('income_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calories.foodspec')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
