# Generated by Django 3.2.6 on 2022-05-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0004_foodspec_incomefoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodspec',
            name='unit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
