# Generated by Django 3.2.6 on 2022-05-26 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calories', '0005_foodspec_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AteFoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_string', models.CharField(max_length=100)),
                ('food_name', models.CharField(max_length=100)),
                ('base_kcal', models.PositiveIntegerField()),
                ('unit_gram', models.PositiveIntegerField()),
                ('many', models.PositiveIntegerField()),
                ('total_unit_gram', models.PositiveIntegerField()),
                ('total_kcal', models.PositiveIntegerField()),
                ('ate_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
