# Generated by Django 3.2.6 on 2022-05-31 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calories', '0008_foodbookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=100)),
                ('mets', models.FloatField()),
                ('order_num', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order_num'],
            },
        ),
        migrations.AlterField(
            model_name='atefoods',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ate_food', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_food_bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
