# Generated by Django 3.2.6 on 2022-06-01 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calories', '0009_auto_20220531_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkedOuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_string', models.CharField(max_length=100)),
                ('workout_name', models.CharField(max_length=100)),
                ('mets', models.FloatField()),
                ('base_kcal', models.PositiveIntegerField()),
                ('many', models.PositiveIntegerField()),
                ('total_kcal', models.PositiveIntegerField()),
                ('workedout_date', models.DateField()),
                ('workedout_start', models.DateTimeField(blank=True, null=True)),
                ('workedout_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_worked_out', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
