# Generated by Django 3.2.6 on 2022-06-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0010_workedouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workedouts',
            name='base_kcal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='workedouts',
            name='total_kcal',
            field=models.FloatField(),
        ),
    ]
