# Generated by Django 3.2.6 on 2022-06-06 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0013_weightandphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightandphoto',
            options={'ordering': ['-save_date', '-created_at']},
        ),
    ]
