# Generated by Django 3.2.6 on 2022-06-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0014_alter_weightandphoto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightandphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
