# Generated by Django 3.2.6 on 2022-06-06 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calories', '0016_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photo_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weightandphoto',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
