# Generated by Django 3.2.6 on 2022-06-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0017_auto_20220606_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightandphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
