# Generated by Django 3.2.6 on 2022-06-10 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0020_alter_weightandphoto_save_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightandphoto',
            options={},
        ),
    ]
